# Generated by Django 4.1.7 on 2023-03-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat11', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterscoreboard',
            name='status',
            field=models.CharField(choices=[('yet_to_bat', 'Yet To Bat'), ('batting', 'Batting'), ('not_out', 'Not Out'), ('out', 'Out')], default='yet_to_bat', max_length=16),
        ),
    ]
